/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package superman;

import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class supplier extends javax.swing.JPanel {

    /**
     * Creates new form customer
     */
    public supplier() {
        initComponents();
        tb_load();
    }
    
    
    
    public void tb_load() {
        
        try {
            DefaultTableModel dt = (DefaultTableModel) s_table.getModel();
            dt.setRowCount(0);
            
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            s_table.setDefaultRenderer(String.class, centerRenderer);
            
            //DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            int numCol = dt.getColumnCount();
            for(int i=0; i<numCol; i++)
            s_table.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
            
            ((DefaultTableCellRenderer)s_table.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            
            Statement s = (Statement) db.mycon().createStatement();
            ResultSet rs = s.executeQuery(" SELECT * FROM supplier");
            
            while(rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                
                dt.addRow(v);
                
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void allset() {
        tb_load();
        
        s_com.setText("");
        s_n.setText("");
        s_tp.setSelectedItem(null);
        s_cn.setText("");
        s_ad.setText("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        s_n = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        s_cn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        s_tp = new javax.swing.JComboBox<>();
        s_com = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        s_ad = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        s_table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        s_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s_n.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        s_n.setAlignmentX(0.0F);
        s_n.setAlignmentY(0.0F);
        s_n.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        s_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_nActionPerformed(evt);
            }
        });
        jPanel2.add(s_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 300, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel2.setText("Proprietor name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel11.setText("Contact no:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel12.setText("Supplier company:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel13.setText("Supplier type:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        s_cn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        s_cn.setAlignmentX(0.0F);
        s_cn.setAlignmentY(0.0F);
        s_cn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        s_cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cnActionPerformed(evt);
            }
        });
        jPanel2.add(s_cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 300, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel15.setText("Address:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));

        s_tp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s_tp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bakery", "Bevarage", "Dairy", "Pharmacy", "Stationary", "Cosmetics", "Drugs", "Clothings", "Butcher", "FIshery", " " }));
        s_tp.setSelectedIndex(-1);
        s_tp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        s_tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_tpActionPerformed(evt);
            }
        });
        jPanel2.add(s_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, 30));

        s_com.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        s_com.setAlignmentX(0.0F);
        s_com.setAlignmentY(0.0F);
        s_com.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        s_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_comActionPerformed(evt);
            }
        });
        jPanel2.add(s_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 300, 30));

        s_ad.setColumns(20);
        s_ad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s_ad.setRows(4);
        s_ad.setTabSize(4);
        s_ad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jScrollPane3.setViewportView(s_ad);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 300, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 490, 360));

        s_table.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        s_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Proprietor name", "Type", "Contact no", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        s_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(s_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 730, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-truck-40.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel6.setText("Suppliers");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 50));

        jTextField7.setBackground(new java.awt.Color(0, 51, 51));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 490, 10));

        s_search.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        s_search.setForeground(new java.awt.Color(153, 153, 153));
        s_search.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        s_search.setText("     Search via comapny name");
        s_search.setAlignmentX(0.0F);
        s_search.setAlignmentY(0.0F);
        s_search.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        s_search.setDoubleBuffered(true);
        s_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s_searchFocusLost(evt);
            }
        });
        s_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_searchActionPerformed(evt);
            }
        });
        s_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                s_searchKeyTyped(evt);
            }
        });
        jPanel1.add(s_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 200, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 100, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 90, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 90, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-25.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void s_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_nActionPerformed

    private void s_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_searchActionPerformed
        // TODO add your handling code here:
        String sr = s_search.getText();
        try{
            Statement s = (Statement) db.mycon().createStatement();

            ResultSet rs = s.executeQuery(" SELECT * FROM supplier WHERE scomp = '"+sr+"'");

            if(rs.next()) {
                s_com.setText(rs.getString("scomp"));
                s_n.setText(rs.getString("sname"));
                s_tp.setSelectedItem(rs.getString("stype"));
                s_cn.setText(rs.getString("scon"));
                s_ad.setText(rs.getString("sadd"));
            }
        } catch (SQLException ex) {
            //Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
            System.out.print(ex);
        }
    }//GEN-LAST:event_s_searchActionPerformed

    private void s_cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_cnActionPerformed

    private void s_tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_tpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_tpActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void s_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_comActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_comActionPerformed

    private void s_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s_searchFocusGained
        // TODO add your handling code here:
        s_search.setText("");
    }//GEN-LAST:event_s_searchFocusGained

    private void s_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s_searchFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s_searchFocusLost

    private void s_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_s_searchKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // supplier add:
        String scom = s_com.getText();
        String sn = s_n.getText();
        String stype = (String)s_tp.getSelectedItem().toString();
        String contact = s_cn.getText();
        String address = s_ad.getText();        
        try{
            Statement s = (Statement) db.mycon().createStatement();
            s.executeUpdate(" INSERT INTO supplier(scomp, sname, stype, scon, sadd) VALUES('"+scom+"','"+sn+"','"+stype+"','"+contact+"','"+address+"') ");
            
        }catch(SQLException e) {
            System.out.println(e);
        }
        
        allset();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Update supplier info:
        String scom = s_com.getText();
        String sn = s_n.getText();
        String stype = (String)s_tp.getSelectedItem().toString();
        String contact = s_cn.getText();
        String address = s_ad.getText();        
        try{
            Statement s = (Statement) db.mycon().createStatement();
            s.executeUpdate(" UPDATE supplier SET scomp = '"+scom+"', sname = '"+sn+"', stype= '"+stype+"', scon = '"+contact+"', sadd = '"+address+"' WHERE scomp = '"+scom+"' ");
            
        }catch(SQLException e) {
            System.out.println(e);
        }
         
        allset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // supplier info delete selected from table:
        DefaultTableModel dt = (DefaultTableModel) s_table.getModel();
        int rw = s_table.getSelectedRow();
        dt.removeRow(rw);
        allset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // search button on employee (mouse click)
        String sr = s_search.getText();
        try{
            Statement s = (Statement) db.mycon().createStatement();

            ResultSet rs = s.executeQuery(" SELECT * FROM supplier WHERE scomp = '"+sr+"'");

            if(rs.next()) {
                s_com.setText(rs.getString("scomp"));
                s_n.setText(rs.getString("sname"));
                s_tp.setSelectedItem(rs.getString("stype"));
                s_cn.setText(rs.getString("scon"));
                s_ad.setText(rs.getString("sadd"));
            }
        } catch (SQLException ex) {
            //Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
            System.out.print(ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextArea s_ad;
    private javax.swing.JTextField s_cn;
    private javax.swing.JTextField s_com;
    private javax.swing.JTextField s_n;
    private javax.swing.JTextField s_search;
    private javax.swing.JTable s_table;
    private javax.swing.JComboBox<String> s_tp;
    // End of variables declaration//GEN-END:variables
}
